baseURL: https://ava-zhao.netlify.app/
languageCode: en
defaultContentLanguage: en
title: Ava Zhao
theme: KeepIt
paginate: 12
enableEmoji: yes
enableRobotsTXT: yes
googleAnalytics: ''
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
blackfriday:
  hrefTargetBlank: yes
  nofollowLinks: yes
  noreferrerLinks: yes
Permalinks:
  posts: /:year/:filename/
menu:
  main:
    - name: Blog
      url: /posts/
      weight: 1
    - name: Categories
      url: /Categories/
      weight: 2
    - name: About
      url: /about
      weight: 3
params:
  author: Ava Zhao
  avatar: /images/me/avatar.jpeg
  baidu_verification: ''
  bing_verification: ''
  cdn_url: ''
  dateFormatToUse: ''
  description: ''
  gitalk:
    clientId: ''
    clientSecret: ''
    owner: ''
    repo: ''
  gitment:
    clientId: ''
    clientSecret: ''
    owner: ''
    repo: ''
  google_verification: ''
  gravatar: {}
  home_mode: ''
  image:
    height: 600
    url: cover.png
    width: 800
  keywords: ''
  license: Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/"
    target="_blank">CC BY-NC 4.0</a>
  logo:
    height: 40
    url: logo.png
    width: 127
  pinterest_verification: ''
  publisher:
    logo:
      height: 40
      url: logo.png
      width: 127
    name: Ava Zhao
  share: 
    copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
  since: 2020
  social:
    Facebook: 
    GitHub: ZWanBing
    Linkedin: 宛冰-赵-5396671aa
    Twitter: 
  socialShare: yes
  subtitle: 随便写写
  utterances:
    owner: ''
    repo: ''
  valine:
    appId: your appId
    appKey: your appKey
    avatar: mm
    enable: no
    language: en
    notify: no
    placeholder: 
    verify: no
    visitor: yes
  yandex_verification: ''
author:
  name: Ava Zhao
